### ISSUE TITLE
Crash In docked mode but works fine in handheld 

### ISSUE THREAD

**Issue by JevilMemer** [masagrator/Status-Monitor-Overlay#36]
So i have this issue with status monitor 

i have no issues with it in handheld mode , i can put the fps counter and everything in handheld mode and then put it in my dock. but the moment i want to access the menu from the tesla menu ,it will crash as soon as i select status monitor 

here is the message file i got from that
[01679784893_420000000007e51a.log](https://github.com/masagrator/Status-Monitor-Overlay/files/11070396/01679784893_420000000007e51a.log)

**Comment by masagrator** [comment]
This is a common issue with overlays in docked mode.

Reports:
https://github.com/WerWolv/libtesla/issues/50
https://github.com/WerWolv/libtesla/issues/64#issuecomment-1477429891

Until somebody figure out the issue and put fix to libtesla, there is not much I can do.

**Comment by masagrator** [comment]
0.8.2 solves the issue

**Comment by zdm65477730** [comment]
@masagrator, I have recompiled all tesla plugs with your patch, including tesla-menu, Edison overlay and Status-Monitor-Overlay, but issue still exits.
If you enable and disable cheat in EdiZon overlay, it will crash later.

The crash type is Data Abort always, it should be relate to Sysmodule memory range, since HOS16 has less system memory left for sysmodules.

But your patch could reduce the crash rate.

**Comment by masagrator** [comment]
```
If you enable and disable cheat in EdiZon overlay, it will crash later.
```
Then this is not an issue with what I fixed as this was a race condition with freeing framebuffer.

**Comment by fennectech** [comment]
@masagrator  Im still seeing this issue.   Have tried recompiling with latest libtesla on other modules.  Tried recompiling the Tesla menu.  Still fataling.  Wolv says ovlloader should be fine.    But yeah. Still fataling while docked n

**Comment by masagrator** [comment]
I am in the middle of testing proper libnx fix instead of using hacks as it seems time needed to revert permissions vary depending on many elements. 

https://github.com/switchbrew/libnx/compare/master...masagrator:libnx:master

**Comment by ELY3M** [comment]
Thank you for letting me know.    proper fix would be much better.

**Comment by masagrator** [comment]
Proper PR can be now found here
https://github.com/switchbrew/libnx/pull/606

**Comment by verbes4** [comment]
my status monitor overlay still crashes in docked mode. was the latest build not compiled with the latest libnx commit?

**Comment by masagrator** [comment]
@verbes4 
You know what? You're right. I have checked release under disassembler and I couldn't find my libnx fix in it even though I didn't touch my fixed libnx library. Dunno why it uninstalled itself.

Check if this file doesn't crash, according
[Status-Monitor-Overlay.zip](https://github.com/masagrator/Status-Monitor-Overlay/files/11337195/Status-Monitor-Overlay.zip)
 to disassembler fixed is applied in this file:

**Comment by verbes4** [comment]
> @verbes4 You know what? You're right. I have checked release in disassembler and I couldn't find my libnx fix in it even though I didn't touch my libnx install. Dunno why it was overwritten.
> 
> Check if this file doesn't crash, according to disassembler fix is applied in this file: [Status-Monitor-Overlay.zip](https://github.com/masagrator/Status-Monitor-Overlay/files/11337195/Status-Monitor-Overlay.zip)

thanks for the build, just tried it but when i try it in docked mode i get error code 2168-0002 :(

**Comment by masagrator** [comment]
You mean when exiting overlay or when entering overlay? Because my fix is related only to when you are exiting from overlay. So if it's crashing when you're entering Status Monitor, that's actually Tesla Menu crashing.

**Comment by verbes4** [comment]
> You mean when exiting overlay or when entering overlay? Because my fix is related only to when you are exiting from overlay. So if it's crashing when you're entering Status Monitor, that's actually Tesla Menu crashing on exit.

ohh sorry for the confusion, i thought it fixed both. exiting is working fine now, thank you :)
